version: 2
branches:
  only:
    - /master-.*/
jobs:
  build:
    docker:
      # specify the version you desire here
      - image: circleci/openjdk:8-jdk

    working_directory: ~/repo

    environment:
      # Customize the JVM maximum heap limit
      TERM: dumb
    
    steps:
      - checkout

      # Download and cache dependencies
      - restore_cache:
          keys:
          - dependencies-{{ .branch }}
          # fallback to using the latest cache if no exact match is found
          - dependencies-

      - run: gradle setupCiWorkspace

      - save_cache:
          paths:
            - ~/.m2
          key: dependencies-{{ .branch }}
        
      - run: gradle build
